"""State schema for the Pedagogical Article Writer graph.

This module defines the ArticleState TypedDict that flows through all nodes
in the LangGraph workflow. Using TypedDict (rather than Pydantic) provides
lightweight type hints without runtime validation overhead, which is the
recommended pattern for internal LangGraph state.
"""

from typing import Annotated, Any
from typing_extensions import TypedDict


def keep_last_non_none(old: Any, new: Any) -> Any:
    """Reducer that keeps the last non-None, non-empty value.

    Used with Annotated[] to protect state fields from being overwritten
    with None or empty string during partial state updates.

    Args:
        old: The existing value in state.
        new: The incoming value from a node's return dict.

    Returns:
        The new value if it's not None/empty, otherwise the old value.
    """
    if new is not None and new != "":
        return new
    return old


class ArticleState(TypedDict):
    """State schema for the pedagogical article writer workflow.

    Each field represents a piece of information that flows through the graph.
    Nodes receive the full state and return partial updates (as plain dicts)
    containing only the fields they want to modify.

    Attributes:
        topic: The user-provided topic for the article. Set via HITL interrupt
            in Phase 2. None until provided.
        approaches: List of generated pedagogical approaches with metaphors.
            Each approach is a dict with 'title' and 'metaphor' keys.
            Generated by the approach agent in Phase 3. None until generated.
        selected_approach_index: Index (0-based) of the user-selected approach.
            Set via HITL interrupt in Phase 4. None until selected.
        rejected_approaches: List of previously rejected approaches. Each is a dict
            with 'title' and 'metaphor' keys. Passed to approach agent to avoid
            repetition when user rejects all approaches and requests regeneration.
            None until first rejection occurs.
        current_draft: The current version of the article being written.
            Updated by the writer agent in Phase 5. None until first draft.
        critic_feedback: Feedback from the critic agent for revision.
            Contains specific issues and improvement suggestions when the critic
            rejects a draft. None when no feedback (initial draft or approved).
            Added in Phase 6 for the reflection loop.
        is_approved: Whether the critic has approved the current draft.
            Set to True when the article passes quality checks OR when max
            iterations (3) is reached.
        revision_count: Number of writer-critic iterations completed.
            Incremented each time the critic rejects and sends back to writer.
            Used to enforce MAX_ITERATIONS (3) termination condition.
        output_path: Path where the final article was saved. Set by
            save_output_node after writing the article to disk. None until
            the article is saved.
    """

    topic: Annotated[str | None, keep_last_non_none]  # Protected from None overwrites
    approaches: list[dict] | None
    selected_approach_index: int | None
    rejected_approaches: list[dict] | None
    current_draft: str | None
    critic_feedback: str | None
    is_approved: bool
    revision_count: int
    output_path: str | None
